### PR TITLE
Add Dropbox Support

### PR DESCRIPTION
**Pull request by rhld16**
### What does this do

- [x] Adds dropbox authentication using the Conversation API
- [x] Adds basic dropbox uploading
- [x] Deletion of older files
- [x] Chunked uploads for bigger files stability (>150MB)

Unfortunately, Dropbox doesn't provide the same fancy device code API as Google or Microsoft but this seems like a suitable alternative. I've added a new bStats point and you may want to change the APP_KEY  and APP_SECRET to your own.

### CODE REVIEW

**Comment by MaxMaeder** [comment]
Looks great! Will merge this this evening.

**Comment by rhld16** [comment]
Sounds good. Since Dropbox allows you to keep file version history [for up to 30 days](https://help.dropbox.com/files-folders/restore-delete/version-history-overview) so maybe uploading two versions (one with date and one without) could be used as the version history doesn't use storage.

**Comment by rhld16** [comment]
I finally got around to add chunked file uploads so files >150MB should upload more stablely

**Comment by MaxMaeder** [comment]
Thanks! Can you give me a basic rundown on how to link a Dropbox account so I can update the docs?

**Comment by rhld16** [comment]
1. Follow the link provided. 
2. Follow the prompts (you may have to login first) and allow DriveBackup to upload files.
3. Copy the resulting code, return to your Minecraft client and paste the code into the chat.

**Comment by MaxMaeder** [comment]
So I am making a release that includes the Dropbox functionality. When I try to link my account, I get an error stating the app has exceeded the max number of users. Can you increase this limit, or alternatively instruct me how to make a new app in the console?

Thanks!

One last thing: you have contributed so much to this project, and I am extremely grateful. Do you have any interest in becoming a maintainter?

Error

**Comment by rhld16** [comment]
My mistake - forgot to open the app to the public lol. Going to have some more time on my hands next week after my exams finish so I’d be happy to be a maintainer

**Pull request merged**
