### PR TITLE
Create Uploader interface to remove duplicate code and add layer of abstraction

### PR DESCRIPTION
**Pull request by frereit**
Changes:

* Added a new interface ratismal.drivebackup.Uploader
* GoogleDriveUploader, OneDriveUploader and FTPUploader implement said interface
* UploadThread now has an ArrayList with all Uploaders which it loops over, instead of having duplicate code for each uploader
* Adding a new uploader is a bit easier now as it just needs to be added to the arraylist (if it's corresponding config value is set

### CODE REVIEW

**Comment by MaxMaeder** [comment]
Looks good, thanks for making these changes. It really cleans up the code. Before I merge, have you tested this on a server?

**Comment by frereit** [comment]
I have tested this and it all seems to work but there is an issue which I just noticed that needs to be addressed before merging.
This change removes the call to ftpUploader.close() so the FTP Connection is not ever closed.

On Java 8 I it would be enough to move the explicit close call to the destructor of the FTPUploader and have the class deal with closing the connection when the object is destroyed but sadly `finalize` has been deprecated. In Java > 8, I think you would use a `Cleaner` but I'm not too sure how that works and if that is the best solution here.

A more generic approach may be to add a close method to the interface but I think that would just add unnecessary clutter, so I think going with the destructor is best. My main goal is to add SCP support which would require a similar `close` functionality as FTP.

What are your thoughts on this?

**Comment by MaxMaeder** [comment]
I think adding a close method to the interface would be fine, especially since multiple upload methods might eventually use it. If you want to figure out how `Cleaner` works, we could use this instead. 

I, unfortunately, don't know much about `Cleaner` either, so I trust your judgment.

**Comment by frereit** [comment]
The fix is done now. Everything seems to work fine, I have tested each Uploader and they all work. I think that makes this PR complete, unless I missed something.

**Pull request merged**
